version: "3"

services:
  web:
    build: 
      context: ./web
    ports:
      - "8080:8080"
  server:
    build: 
      context: ./server
    environment:
      - PORT=80
      - MODELPORT=8080
  e0model:
    build:
      context: ./ml
      dockerfile: e0.dockerfile
    environment:
      - PORT=8080
  i1model:
    build:
      context: ./ml
      dockerfile: i1.dockerfile
    environment:
      - PORT=8080
