version: "3"

# prod environment
# this file extends docker-compose.yml
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  web:
    build:
      context: ./web
      dockerfile: prod.dockerfile
  server:
    command: yarn start
    environment:
      - PORT=80
