version: "3"

services:
  web:
    build: 
      context: ./web
    command: yarn dev
    volumes:
      - ./web:/code
    ports:
      - "8080:8080"
  server:
    build: 
      context: ./server
    command: yarn dev
    volumes:
      - ./server:/code
    ports:
      - "8000:3000"
      - "5858:5858"
    environment:
      - PORT=3000
      - MODELPORT=8080
  e0model:
    build:
      context: ./ml
      dockerfile: e0.dockerfile
    environment:
      - PORT=8080
  i1model:
    build:
      context: ./ml
      dockerfile: i1.dockerfile
    environment:
      - PORT=8080
